---
title:  群落系统发育研究不能脱离理论框架
author: "Jinlong Zhang"
date: "2020-12-29"
output: html_document
---


导读

群落系统发育（community phylogenetics）研究最初是为了探讨群落内物种共存而提出的，但近些年不少研究逐渐脱离了其理论框架，如（1）有些研究将系统发育理论框架用于群落以外的地理尺度，但没有充分考虑地理和历史过程的影响；（2）缺乏对物种的功能性状进行系统发育信号（Phylogenetic signal）检验；（3）将群落内的部分种类（如特有种、外来种、入侵种等）分出来，分别计算群落系统发育指数，但是仍然按照群落物种共存的理论框架去推断各种生态学过程的相对重要性。这些做法严重偏离了群落物种共存的理论框架，所做推断可能是毫无意义的。

本文首先介绍了什么是系统发育指数（Net Relatedness Index, NRI）、零模型（Null models）并介绍了其相关的生态和统计意义，随后探讨了为什么将部分种（如入侵种、特有种）从群落中提出来计算群落系统发育指数（NRI）是不可取的，并探讨了常见的群落系统发育理论框架被误用的不同情形。

本文主要是根据近期回复的邮件整理的，因此为问答体。因本人学识有限，有很多地方可能存在认知不足甚至错误，此处主要是希望抛砖引玉，欢迎读者共同探讨。



*问：啥是NRI？*

答：NRI是Net relatedness index的缩写，是根据群落内出现的物种之间的系统发育平均距离（MPD_observerd, Mean Pairwised Phylogenetic Distance），再用零模型生成群落的物种之间的系统发育平均距离(MPD_null)标准化之后计算出来的，其公式为：

NRI = -1*(MPD_observerd-mean(MPD_null))/sd(MPD_null)。

因此，NRI其实是Standard Effective Size（SES）加一个负号，与数据标准化（standardisation）十分相似。



*问：啥是零模型（null model）？*

群落系统发育研究中的零模型是物种随机化的方法，例如tip-shuffling是将物种的标签在进化树上随机打乱，从而获得物种完全随机排列时MPD的统计分布，如进行999次随机化，就生成了999个随机化后的群落，再分别计算这些群落的系统发育平均距离（MPD），最终得到999个MPD_null。由于NRI的计算涉及的零模型有多种，所以要注意零模型的选择，具体可参考PhyloCom或者picante软件的说明。



*问：NRI本身有统计意义吗？*

答：NRI是有统计意义的，因为NRI的本质是standard effective size。有些作者假设NRI符合正态分布，则-1.96或者1.96就是其95%置信区间的阈值。



*问：研究发现，外来种的NRI指数随着海拔升高而降低，如果将外来种从群落中提出来，专门计算群落中外来种的NRI，有生态学意义吗？*

答：外来种的NRI指数随着海拔升高而降低，表面上是可以说在高海拔地区外来种在系统发育上相比低海拔不那么聚集。不过，NRI是和物种数有一定关系的。这主要是由于MPD的值取决于物种在整个地区进化树上的分布。物种数越多，某一个样方的物种在进化树上占有的比例就越高，也越可能呈现出系统发育发散的情况。目前还没有看到一种有效的方法能够用物种数将NRI标准化。



*问：比较群落中外来种NRI和特有种的NRI是否有生态学意义？*

答：在提出NRI时，Webb等人主要是为了探讨群落的物种共存机制。在他们的理论框架中，如果群落内物种的功能性状在进化树上是保守的，也就是有显著的系统发育信号（Phylogenetic signal），同时，如果群落内物种的系统发育关系与随机的群落（就是零模型群落）相比显著聚集或者发散（超过观测值的97.5%上分位数或者低于2.5%下分位数）就说明群落组成很可能不是随机的。既然物种组成不是随机的，则应该认为生态位过程（niche-based process）起着重要作用，意味着生境对物种性状有很强的筛选作用（environmental filtering），导致群落呈现出观察到的物种组成。

起初，Webb的研究是在Gunung Palung大样地中进行的，他只分析了DBH>10cm的木本植物，继而探讨了NRI指数的意义等。对于他所研究的问题，上述处理在某种程度上是合理的。但是，后续有很多研究在并不满足Webb等提出的理论框架下仍然按照其理论框架推断各种生态学过程，这些分析和推断在很大程度上可能是错误的。

主要表现在：

1. **没有对物种的功能性状进行系统发育信号检验。**物种共存往往是通过功能性状起作用的，只有系统发育关系相近的种拥有相似的功能性状，也就是存在显著的系统发育信号时，Webb等的理论框架才能成立，而很多研究往往没有做这个检验，因此并不一定满足群落系统发育理论框架。
2. **所研究物种在群落间不能自由传播。**将某一个类群，或者符合某种地理分布类型的物种，如中国特有种、外来种等专门拿出来计算NRI，虽然从技术上NRI可以计算，但在一定程度上并没有满足群落系统发育分析的理论框架。这主要是因为，这些分析不能保证入侵种在所有样地已经“完全入侵”，受到入侵种传播先后的影响，在有些地段，入侵种还处于入侵早期，或者还没有开始入侵，但是如果将这种格局归结于生态位过程的影响，生态位过程在物种共存中的作用就会被高估。
3. **忽略种间相互作用的影响。**Webb等的理论框架一般将群落内所有种间相互作用考虑为随机过程，这些相互作用是难以量化的。如果只考虑群落中的一部分种，可能会造成这些种和其他未考虑的种之间种间相互作用如竞争（competition）、促进（facilitation）被完全忽略。研究表明，种间相互作用对群落物种共存有很显著的影响。举例来说，在植被较好的地段，外来种较难入侵，这种情况，按照群落物种共存的理论框架，生态位过程的作用就会被高估。
4. **零模型的物种库选择不当。**NRI计算中涉及的零模型，很可能与物种数、物种库（species pool）的选择有很紧密的关系。若计算NRI时的零模型没有经过物种丰富度校正，那很可能就不能对NRI进行比较。用于计算两个NRI的零模型群落，物种库的范围也可能不同。例如，计算外来种NRI的零模型中，物种也可能都是外来种，但是计算特有种NRI的零模型中，物种很可能为特有种，这就造成了物种组成随机化的基准不同，偏离了群落系统发育的理论框架。
5. **在地理尺度的物种组成研究中，没有充分考虑气候、地质历史以及进化过程的影响。**生物地理研究一般是在较大的空间尺度开展的，在这种空间尺度下，物种可能并不能在研究的区域内自由传播（dispersal）、定植（colonisation）和存活（persistence），如样方或采样区域存在很高的海拔差异，或者分散在几百到几千平方公里的范围内，而同时物种存在同域或者异域物种形成，且不少地区物种分布又受到冰期、全球变暖等的影响，这种情况下，群落物种共存的理论框架并不适用，讨论物种共存时必须要考虑不同尺度的生态学过程以及气候、历史事件的影响。
6. **分析中忽略人为干扰的作用。**实际观察到的群落往往都受到不同程度人为干扰，而人为干扰对于群落的物种组成的影响非常大。群落内物种组成的恢复也可能需要几百年到上千年，同时也可能受到如优先效应（priority effect）以及演替锁定（arrested succession）的影响。即使物种在研究区域内能够自由传播，也并不意味着其能够自由定植、生长，因此，在人为干扰严重的地段，进行群落系统发育研究时必须考虑人为干扰以及其他生态学过程的影响。

综上，比较外来种和特有种的群落系统发育结构是要非常慎重的，因为如果不满足理论框架，比较相关指数就不能帮忙解决物种共存机制上的理论问题，此时做出“随机过程主导”或者“生态位过程主导”的推论也就毫无意义了。